### ISSUE TITLE
Solution lacks ApiWrappers

### ISSUE THREAD

**Issue by tymurbaniak** [mpxx24/wyspaBotWebApp#1]
There is no WikipediaApiWrapper nor SpotifyApiWrapper. Solution won't build without them.

**Comment by mpxx24** [comment]
added new project and updated references

**Comment by mpxx24** [comment]
@tymurbaniak please let me know if error still occurs, and what is the exact problem

**Comment by tymurbaniak** [comment]
There is still 
ERROR: CS0246	The type or namespace name 'SpotifyApiWrapper' could not be found (are you missing a using directive or an assembly reference?)

Solution lacks api wrapper for Spotify.

**Comment by mpxx24** [comment]
@tymurbaniak added libs folder
